/**
 * Moisturizers Database - Global Products
 * Lightweight, rich, gel-creams, sleeping masks
 */

import { GlobalProduct } from '../product-database-structure';

export const MOISTURIZERS: GlobalProduct[] = [
  // Lightweight Moisturizers
  {
    id: 'cerave_daily_moisturizer',
    name: 'Daily Moisturizing Lotion',
    brand: 'CeraVe',
    category: 'moisturizers',
    subcategory: 'lightweight-moisturizers',
    description: 'A lightweight, oil-free moisturizer with ceramides and hyaluronic acid to hydrate and restore the skin barrier.',
    images: [
      { url: 'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Glycerin',
      'Caprylic/Capric Triglyceride',
      'Cetearyl Alcohol',
      'Ceramide NP',
      'Ceramide AP',
      'Ceramide EOP',
      'Hyaluronic Acid',
      'Dimethicone',
      'Polysorbate 20',
      'Polyglyceryl-3 Diisostearate',
      'Potassium Phosphate',
      'Dipropylene Glycol',
      'Sodium Lauroyl Lactylate',
      'Disodium EDTA',
      'Methylparaben',
      'Propylparaben',
      'Carbomer',
      'Xanthan Gum',
    ],
    size: '355ml',
    priceRange: { min: 12, max: 18, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$12-18', currency: 'USD', retailer: 'amazon' },
      { country: 'Canada', countryCode: 'CA', available: true, price: 'CA$15-22', currency: 'CAD', retailer: 'amazon' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£10-15', currency: 'GBP', retailer: 'amazon' },
      { country: 'Australia', countryCode: 'AU', available: true, price: 'AU$18-25', currency: 'AUD', retailer: 'amazon' },
    ],
    targetSkinTypes: ['dry', 'normal', 'sensitive'],
    targetConcerns: ['dryness', 'barrier repair', 'hydration'],
    keyIngredients: ['Ceramide NP', 'Hyaluronic Acid', 'Glycerin'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['drugstore', 'ceramides', 'fragrance-free', 'barrier-repair'],
  },
  {
    id: 'cetaphil_daily_moisturizer',
    name: 'Daily Hydrating Moisturizer',
    brand: 'Cetaphil',
    category: 'moisturizers',
    subcategory: 'lightweight-moisturizers',
    description: 'A lightweight, non-comedogenic moisturizer with hyaluronic acid to hydrate without clogging pores.',
    images: [
      { url: 'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Glycerin',
      'Dicaprylyl Carbonate',
      'Cyclopentasiloxane',
      'Glycine Soja Oil',
      'Hydroxyethyl Urea',
      'Glyceryl Stearate',
      'PEG-100 Stearate',
      'Sodium PCA',
      'Tocopherol',
      'Dimethicone',
      'Carbomer',
      'Sodium Hydroxide',
      'Phenoxyethanol',
      'Ethylhexylglycerin',
    ],
    size: '88ml',
    priceRange: { min: 10, max: 15, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$10-15', currency: 'USD', retailer: 'amazon' },
      { country: 'Canada', countryCode: 'CA', available: true, price: 'CA$12-18', currency: 'CAD', retailer: 'amazon' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£8-12', currency: 'GBP', retailer: 'amazon' },
    ],
    targetSkinTypes: ['dry', 'normal', 'sensitive'],
    targetConcerns: ['dryness', 'hydration', 'sensitivity'],
    keyIngredients: ['Glycerin', 'Sodium PCA', 'Tocopherol'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['drugstore', 'hydrating', 'non-comedogenic'],
  },
  {
    id: 'neutrogena_hydro_boost',
    name: 'Hydro Boost Water Gel',
    brand: 'Neutrogena',
    category: 'moisturizers',
    subcategory: 'gel-creams',
    description: 'An oil-free, lightweight gel moisturizer with hyaluronic acid for intense hydration.',
    images: [
      { url: 'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Dimethicone',
      'Glycerin',
      'Dimethicone/Vinyl Dimethicone Crosspolymer',
      'Sodium Hyaluronate',
      'Polyacrylamide',
      'C13-14 Isoparaffin',
      'Laureth-7',
      'Phenoxyethanol',
      'Dimethiconol',
      'Ethylhexylglycerin',
      'Laureth-23',
      'Sodium Hydroxide',
      'Disodium EDTA',
      'Blue 1',
      'Yellow 5',
    ],
    size: '50ml',
    priceRange: { min: 15, max: 20, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$15-20', currency: 'USD', retailer: 'amazon' },
      { country: 'Canada', countryCode: 'CA', available: true, price: 'CA$18-25', currency: 'CAD', retailer: 'amazon' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£12-16', currency: 'GBP', retailer: 'amazon' },
    ],
    targetSkinTypes: ['oily', 'combination', 'normal'],
    targetConcerns: ['hydration', 'oiliness'],
    keyIngredients: ['Sodium Hyaluronate', 'Glycerin', 'Dimethicone'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['drugstore', 'gel-cream', 'oil-free', 'hydrating'],
  },
  {
    id: 'laneige_water_bank',
    name: 'Water Bank Hyaluronic Cream',
    brand: 'Laneige',
    category: 'moisturizers',
    subcategory: 'lightweight-moisturizers',
    description: 'A hydrating cream with hyaluronic acid and mineral water for intense moisture.',
    images: [
      { url: 'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Glycerin',
      'Sodium Hyaluronate',
      'Butylene Glycol',
      'Dimethicone',
      'Ceramide NP',
      'Mineral Water',
      'Betaine',
      'Allantoin',
      'Caprylyl Glycol',
      'Ethylhexylglycerin',
      'Phenoxyethanol',
    ],
    size: '50ml',
    priceRange: { min: 32, max: 38, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$32-38', currency: 'USD', retailer: 'sephora' },
      { country: 'South Korea', countryCode: 'KR', available: true, price: '₩45,000-55,000', currency: 'KRW', retailer: 'yesstyle' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£28-35', currency: 'GBP', retailer: 'cult-beauty' },
    ],
    targetSkinTypes: ['dry', 'normal', 'combination'],
    targetConcerns: ['dryness', 'hydration'],
    keyIngredients: ['Sodium Hyaluronate', 'Ceramide NP', 'Mineral Water'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['k-beauty', 'hydrating', 'ceramides'],
  },
  {
    id: 'la_roche_posay_toleriane',
    name: 'Toleriane Double Repair Face Moisturizer',
    brand: 'La Roche-Posay',
    category: 'moisturizers',
    subcategory: 'lightweight-moisturizers',
    description: 'A gentle moisturizer with ceramides and niacinamide for sensitive skin barrier repair.',
    images: [
      { url: 'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Glycerin',
      'Dimethicone',
      'Niacinamide',
      'Ceramide NP',
      'Ceramide AP',
      'Ceramide EOP',
      'Tocopherol',
      'Caprylyl Glycol',
      'Phenoxyethanol',
      'Carbomer',
      'Sodium Hydroxide',
    ],
    size: '75ml',
    priceRange: { min: 20, max: 25, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$20-25', currency: 'USD', retailer: 'ulta' },
      { country: 'France', countryCode: 'FR', available: true, price: '€18-22', currency: 'EUR', retailer: 'sephora' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£16-20', currency: 'GBP', retailer: 'boots' },
    ],
    targetSkinTypes: ['sensitive', 'dry', 'normal'],
    targetConcerns: ['sensitivity', 'barrier repair', 'redness'],
    keyIngredients: ['Niacinamide', 'Ceramide NP', 'Tocopherol'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['french-pharmacy', 'sensitive-skin', 'ceramides', 'fragrance-free'],
  },
  {
    id: 'belif_aqua_bomb',
    name: 'The True Cream Aqua Bomb',
    brand: 'Belif',
    category: 'moisturizers',
    subcategory: 'gel-creams',
    description: 'A lightweight gel-cream with herbal extracts for intense hydration.',
    images: [
      { url: 'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Glycerin',
      'Butylene Glycol',
      'Sodium Hyaluronate',
      'Herbal Extracts',
      'Dimethicone',
      'Caprylyl Glycol',
      'Ethylhexylglycerin',
      'Phenoxyethanol',
    ],
    size: '50ml',
    priceRange: { min: 38, max: 42, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$38-42', currency: 'USD', retailer: 'sephora' },
      { country: 'South Korea', countryCode: 'KR', available: true, price: '₩50,000-60,000', currency: 'KRW', retailer: 'yesstyle' },
    ],
    targetSkinTypes: ['oily', 'combination', 'normal'],
    targetConcerns: ['hydration', 'oiliness'],
    keyIngredients: ['Sodium Hyaluronate', 'Herbal Extracts', 'Glycerin'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['k-beauty', 'gel-cream', 'hydrating'],
  },
  {
    id: 'tatcha_dew_cream',
    name: 'The Dewy Skin Cream',
    brand: 'Tatcha',
    category: 'moisturizers',
    subcategory: 'rich-moisturizers',
    description: 'A rich, plumping cream with Japanese purple rice and hyaluronic acid.',
    images: [
      { url: 'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Glycerin',
      'Squalane',
      'Sodium Hyaluronate',
      'Japanese Purple Rice',
      'Ceramides',
      'Tocopherol',
      'Caprylyl Glycol',
      'Phenoxyethanol',
    ],
    size: '50ml',
    priceRange: { min: 68, max: 75, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$68-75', currency: 'USD', retailer: 'sephora' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£55-65', currency: 'GBP', retailer: 'cult-beauty' },
    ],
    targetSkinTypes: ['dry', 'normal'],
    targetConcerns: ['dryness', 'hydration', 'plumping'],
    keyIngredients: ['Sodium Hyaluronate', 'Squalane', 'Ceramides'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['luxury', 'japanese-inspired', 'hydrating'],
  },
];


