/**
 * Serums Database - Global Products
 * Hydrating, anti-aging, brightening, acne, vitamin C, retinol, peptide serums
 */

import { GlobalProduct } from '../product-database-structure';

export const SERUMS: GlobalProduct[] = [
  // Hyaluronic Acid Serums
  {
    id: 'ordinary_hyaluronic_acid',
    name: 'Hyaluronic Acid 2% + B5',
    brand: 'The Ordinary',
    category: 'serums',
    subcategory: 'hydrating-serums',
    description: 'A hydrating serum with multiple weights of hyaluronic acid to hydrate and plump the skin.',
    images: [
      { url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Sodium Hyaluronate',
      'Sodium Hyaluronate Crosspolymer',
      'Hyaluronic Acid',
      'Panthenol',
      'Glycerin',
      'Propanediol',
      '1,2-Hexanediol',
      'Caprylyl Glycol',
      'Trisodium Ethylenediamine Disuccinate',
      'Citric Acid',
      'Isoceteth-20',
      'Polysorbate 20',
    ],
    size: '30ml',
    priceRange: { min: 6, max: 8, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$6-8', currency: 'USD', retailer: 'amazon' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£5-7', currency: 'GBP', retailer: 'cult-beauty' },
      { country: 'Canada', countryCode: 'CA', available: true, price: 'CA$8-10', currency: 'CAD', retailer: 'amazon' },
      { country: 'Australia', countryCode: 'AU', available: true, price: 'AU$10-14', currency: 'AUD', retailer: 'amazon' },
    ],
    targetSkinTypes: ['dry', 'normal', 'oily', 'combination'],
    targetConcerns: ['dryness', 'fine lines', 'hydration'],
    keyIngredients: ['Sodium Hyaluronate', 'Hyaluronic Acid', 'Panthenol'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['affordable', 'hydrating', 'fragrance-free', 'vegan'],
  },
  {
    id: 'vichy_mineral_89',
    name: 'Mineral 89 Hyaluronic Acid Serum',
    brand: 'Vichy',
    category: 'serums',
    subcategory: 'hydrating-serums',
    description: 'A lightweight hyaluronic acid serum with 89% Vichy Mineralizing Water to strengthen skin barrier.',
    images: [
      { url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Vichy Mineralizing Water',
      'Hyaluronic Acid',
      'Caprylyl Glycol',
      'Glycerin',
      'Phenoxyethanol',
      'Citric Acid',
    ],
    size: '50ml',
    priceRange: { min: 25, max: 30, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$25-30', currency: 'USD', retailer: 'ulta' },
      { country: 'France', countryCode: 'FR', available: true, price: '€22-28', currency: 'EUR', retailer: 'sephora' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£20-25', currency: 'GBP', retailer: 'boots' },
    ],
    targetSkinTypes: ['all'],
    targetConcerns: ['dryness', 'hydration', 'barrier repair'],
    keyIngredients: ['Hyaluronic Acid', 'Vichy Mineralizing Water'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['french-pharmacy', 'hydrating', 'fragrance-free'],
  },

  // Niacinamide Serums
  {
    id: 'ordinary_niacinamide',
    name: 'Niacinamide 10% + Zinc 1%',
    brand: 'The Ordinary',
    category: 'serums',
    subcategory: 'acne-serums',
    description: 'A high-strength niacinamide serum to reduce blemishes and balance sebum production.',
    images: [
      { url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Niacinamide',
      'Zinc PCA',
      'Dimethyl Isosorbide',
      'Tamarinus Indica Seed Gum',
      'Isoceteth-20',
      'Phenoxyethanol',
      'Chlorphenesin',
    ],
    size: '30ml',
    priceRange: { min: 6, max: 8, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$6-8', currency: 'USD', retailer: 'amazon' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£5-7', currency: 'GBP', retailer: 'cult-beauty' },
      { country: 'Canada', countryCode: 'CA', available: true, price: 'CA$8-10', currency: 'CAD', retailer: 'amazon' },
    ],
    targetSkinTypes: ['oily', 'combination', 'acne-prone'],
    targetConcerns: ['acne', 'pores', 'oiliness', 'hyperpigmentation'],
    keyIngredients: ['Niacinamide', 'Zinc PCA'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['affordable', 'acne-friendly', 'pore-minimizing', 'vegan'],
  },
  {
    id: 'paula_choice_niacinamide',
    name: '10% Niacinamide Booster',
    brand: "Paula's Choice",
    category: 'serums',
    subcategory: 'brightening-serums',
    description: 'A concentrated niacinamide serum to minimize pores, reduce redness, and improve skin texture.',
    images: [
      { url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Niacinamide',
      'Acetyl Glucosamine',
      'Butylene Glycol',
      'Glycerin',
      'Allantoin',
      'Sodium Hyaluronate',
      'Dipropylene Glycol',
      'Sodium PCA',
      'Ceramide NP',
      'Phytosphingosine',
      'Cholesterol',
      'Sodium Lauroyl Lactylate',
      'Carbomer',
      'Polysorbate 20',
      'Disodium EDTA',
      'Ethylhexylglycerin',
      'Phenoxyethanol',
    ],
    size: '20ml',
    priceRange: { min: 35, max: 42, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$35-42', currency: 'USD', retailer: 'sephora' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£28-35', currency: 'GBP', retailer: 'cult-beauty' },
      { country: 'Canada', countryCode: 'CA', available: true, price: 'CA$45-55', currency: 'CAD', retailer: 'sephora' },
    ],
    targetSkinTypes: ['oily', 'combination', 'normal'],
    targetConcerns: ['pores', 'texture', 'redness', 'hyperpigmentation'],
    keyIngredients: ['Niacinamide', 'Acetyl Glucosamine', 'Ceramide NP'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['premium', 'pore-minimizing', 'barrier-repair'],
  },
  {
    id: 'glossier_super_pure',
    name: 'Super Pure Niacinamide + Zinc Serum',
    brand: 'Glossier',
    category: 'serums',
    subcategory: 'acne-serums',
    description: 'A gentle niacinamide serum to calm redness and reduce breakouts.',
    images: [
      { url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Niacinamide',
      'Zinc PCA',
      'Glycerin',
      'Sodium Hyaluronate',
      'Allantoin',
      'Betaine',
      'Caprylyl Glycol',
      'Ethylhexylglycerin',
      'Phenoxyethanol',
    ],
    size: '30ml',
    priceRange: { min: 28, max: 32, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$28-32', currency: 'USD', retailer: 'amazon' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£22-28', currency: 'GBP', retailer: 'amazon' },
    ],
    targetSkinTypes: ['sensitive', 'oily', 'acne-prone'],
    targetConcerns: ['acne', 'redness', 'sensitivity'],
    keyIngredients: ['Niacinamide', 'Zinc PCA', 'Allantoin'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['gentle', 'sensitive-skin', 'acne-friendly'],
  },

  // Vitamin C Serums
  {
    id: 'ordinary_vitamin_c_suspension',
    name: 'Vitamin C Suspension 23% + HA Spheres 2%',
    brand: 'The Ordinary',
    category: 'serums',
    subcategory: 'vitamin-c-serums',
    description: 'A high-strength vitamin C serum for brightening and anti-aging benefits.',
    images: [
      { url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Dimethyl Isosorbide',
      'Ascorbic Acid',
      'Sodium Hyaluronate Crosspolymer',
      'Tocopherol',
      'Isoceteth-20',
      'Polysorbate 20',
      'Phenoxyethanol',
      'Chlorphenesin',
    ],
    size: '30ml',
    priceRange: { min: 6, max: 8, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$6-8', currency: 'USD', retailer: 'amazon' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£5-7', currency: 'GBP', retailer: 'cult-beauty' },
    ],
    targetSkinTypes: ['normal', 'oily', 'combination'],
    targetConcerns: ['hyperpigmentation', 'dark spots', 'fine lines', 'brightening'],
    keyIngredients: ['Ascorbic Acid', 'Sodium Hyaluronate Crosspolymer', 'Tocopherol'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['affordable', 'brightening', 'anti-aging', 'high-strength'],
  },
  {
    id: 'skinceuticals_ce_ferulic',
    name: 'C E Ferulic',
    brand: 'SkinCeuticals',
    category: 'serums',
    subcategory: 'vitamin-c-serums',
    description: 'A professional-grade vitamin C serum with L-ascorbic acid, vitamin E, and ferulic acid.',
    images: [
      { url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Ascorbic Acid',
      'Tocopherol',
      'Ferulic Acid',
      'Glycerin',
      'Laureth-23',
      'Phenoxyethanol',
    ],
    size: '30ml',
    priceRange: { min: 160, max: 180, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$160-180', currency: 'USD', retailer: 'sephora' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£130-150', currency: 'GBP', retailer: 'cult-beauty' },
      { country: 'Canada', countryCode: 'CA', available: true, price: 'CA$200-230', currency: 'CAD', retailer: 'sephora' },
    ],
    targetSkinTypes: ['all'],
    targetConcerns: ['hyperpigmentation', 'fine lines', 'brightening', 'anti-aging'],
    keyIngredients: ['Ascorbic Acid', 'Tocopherol', 'Ferulic Acid'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['luxury', 'professional-grade', 'brightening', 'anti-aging'],
  },
  {
    id: 'drunk_elephant_c_firma',
    name: 'C-Firma Vitamin C Day Serum',
    brand: 'Drunk Elephant',
    category: 'serums',
    subcategory: 'vitamin-c-serums',
    description: 'A brightening vitamin C serum with L-ascorbic acid, ferulic acid, and vitamin E.',
    images: [
      { url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Ascorbic Acid',
      'Tocopherol',
      'Ferulic Acid',
      'Glycerin',
      'Sodium Hyaluronate',
      'Pumpkin Ferment Extract',
      'Pomegranate Extract',
      'Grape Juice Extract',
      'Apple Extract',
      'Lentil Extract',
      'Cucumber Extract',
      'Phenoxyethanol',
      'Caprylyl Glycol',
    ],
    size: '30ml',
    priceRange: { min: 78, max: 85, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$78-85', currency: 'USD', retailer: 'sephora' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£65-75', currency: 'GBP', retailer: 'cult-beauty' },
      { country: 'Canada', countryCode: 'CA', available: true, price: 'CA$100-110', currency: 'CAD', retailer: 'sephora' },
    ],
    targetSkinTypes: ['all'],
    targetConcerns: ['hyperpigmentation', 'dark spots', 'brightening', 'fine lines'],
    keyIngredients: ['Ascorbic Acid', 'Tocopherol', 'Ferulic Acid'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['premium', 'brightening', 'clean-beauty'],
  },

  // Retinol Serums
  {
    id: 'ordinary_retinol_05',
    name: 'Retinol 0.5% in Squalane',
    brand: 'The Ordinary',
    category: 'serums',
    subcategory: 'retinol-serums',
    description: 'A water-free solution with 0.5% pure retinol in squalane for anti-aging benefits.',
    images: [
      { url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Squalane',
      'Retinol',
      'Rosmarinus Officinalis Leaf Extract',
      'Tocopherol',
    ],
    size: '30ml',
    priceRange: { min: 8, max: 10, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$8-10', currency: 'USD', retailer: 'amazon' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£7-9', currency: 'GBP', retailer: 'cult-beauty' },
      { country: 'Canada', countryCode: 'CA', available: true, price: 'CA$10-12', currency: 'CAD', retailer: 'amazon' },
    ],
    targetSkinTypes: ['normal', 'oily', 'combination'],
    targetConcerns: ['fine lines', 'wrinkles', 'texture', 'acne'],
    keyIngredients: ['Retinol', 'Squalane', 'Tocopherol'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['affordable', 'anti-aging', 'retinol', 'vegan'],
  },
  {
    id: 'ordinary_retinol_1',
    name: 'Retinol 1% in Squalane',
    brand: 'The Ordinary',
    category: 'serums',
    subcategory: 'retinol-serums',
    description: 'A high-strength retinol serum for advanced anti-aging benefits.',
    images: [
      { url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Squalane',
      'Retinol',
      'Rosmarinus Officinalis Leaf Extract',
      'Tocopherol',
    ],
    size: '30ml',
    priceRange: { min: 9, max: 11, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$9-11', currency: 'USD', retailer: 'amazon' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£8-10', currency: 'GBP', retailer: 'cult-beauty' },
    ],
    targetSkinTypes: ['normal', 'oily', 'combination'],
    targetConcerns: ['fine lines', 'wrinkles', 'texture', 'acne'],
    keyIngredients: ['Retinol', 'Squalane', 'Tocopherol'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['affordable', 'anti-aging', 'high-strength', 'retinol'],
  },
  {
    id: 'paula_choice_retinol',
    name: 'Clinical 1% Retinol Treatment',
    brand: "Paula's Choice",
    category: 'serums',
    subcategory: 'retinol-serums',
    description: 'A potent retinol treatment with 1% retinol and peptides for advanced anti-aging.',
    images: [
      { url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Retinol',
      'Peptides',
      'Ceramides',
      'Niacinamide',
      'Glycerin',
      'Sodium Hyaluronate',
      'Tocopherol',
      'Allantoin',
      'Butylene Glycol',
      'Caprylyl Glycol',
      'Phenoxyethanol',
    ],
    size: '30ml',
    priceRange: { min: 45, max: 52, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$45-52', currency: 'USD', retailer: 'sephora' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£38-45', currency: 'GBP', retailer: 'cult-beauty' },
    ],
    targetSkinTypes: ['normal', 'oily', 'combination'],
    targetConcerns: ['fine lines', 'wrinkles', 'texture', 'anti-aging'],
    keyIngredients: ['Retinol', 'Peptides', 'Ceramides', 'Niacinamide'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['premium', 'anti-aging', 'retinol', 'peptides'],
  },

  // Peptide Serums
  {
    id: 'ordinary_buffet',
    name: 'Buffet + Copper Peptides 1%',
    brand: 'The Ordinary',
    category: 'serums',
    subcategory: 'peptide-serums',
    description: 'A multi-peptide serum with copper peptides for anti-aging and skin repair.',
    images: [
      { url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Copper Peptides',
      'Multiple Peptides',
      'Glycerin',
      'Sodium Hyaluronate',
      'Butylene Glycol',
      '1,2-Hexanediol',
      'Caprylyl Glycol',
      'Phenoxyethanol',
    ],
    size: '30ml',
    priceRange: { min: 28, max: 32, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$28-32', currency: 'USD', retailer: 'amazon' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£22-28', currency: 'GBP', retailer: 'cult-beauty' },
    ],
    targetSkinTypes: ['all'],
    targetConcerns: ['fine lines', 'wrinkles', 'anti-aging', 'skin repair'],
    keyIngredients: ['Copper Peptides', 'Multiple Peptides', 'Sodium Hyaluronate'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['affordable', 'anti-aging', 'peptides', 'multi-peptide'],
  },

  // Brightening Serums
  {
    id: 'ordinary_alpha_arbutin',
    name: 'Alpha Arbutin 2% + HA',
    brand: 'The Ordinary',
    category: 'serums',
    subcategory: 'brightening-serums',
    description: 'A brightening serum with alpha arbutin to reduce hyperpigmentation and dark spots.',
    images: [
      { url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Alpha Arbutin',
      'Sodium Hyaluronate',
      'Glycerin',
      'Butylene Glycol',
      '1,2-Hexanediol',
      'Caprylyl Glycol',
      'Phenoxyethanol',
    ],
    size: '30ml',
    priceRange: { min: 8, max: 10, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$8-10', currency: 'USD', retailer: 'amazon' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£7-9', currency: 'GBP', retailer: 'cult-beauty' },
    ],
    targetSkinTypes: ['all'],
    targetConcerns: ['hyperpigmentation', 'dark spots', 'brightening'],
    keyIngredients: ['Alpha Arbutin', 'Sodium Hyaluronate'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['affordable', 'brightening', 'hyperpigmentation'],
  },
  {
    id: 'glow_recipe_plum_plump',
    name: 'Plum Plump Hyaluronic Acid Serum',
    brand: 'Glow Recipe',
    category: 'serums',
    subcategory: 'hydrating-serums',
    description: 'A hydrating serum with hyaluronic acid and plum extract for plumping and hydration.',
    images: [
      { url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Sodium Hyaluronate',
      'Plum Extract',
      'Glycerin',
      'Niacinamide',
      'Allantoin',
      'Butylene Glycol',
      'Caprylyl Glycol',
      'Phenoxyethanol',
    ],
    size: '30ml',
    priceRange: { min: 34, max: 38, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$34-38', currency: 'USD', retailer: 'sephora' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£28-32', currency: 'GBP', retailer: 'cult-beauty' },
    ],
    targetSkinTypes: ['all'],
    targetConcerns: ['dryness', 'hydration', 'plumping'],
    keyIngredients: ['Sodium Hyaluronate', 'Plum Extract', 'Niacinamide'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['premium', 'hydrating', 'k-beauty-inspired'],
  },
];


