/**
 * Sunscreens Database - Global Products
 * Mineral, chemical, tinted, spray sunscreens
 */

import { GlobalProduct } from '../product-database-structure';

export const SUNSCREENS: GlobalProduct[] = [
  // Mineral Sunscreens
  {
    id: 'cerave_mineral_sunscreen',
    name: 'Mineral Sunscreen SPF 50',
    brand: 'CeraVe',
    category: 'sunscreens',
    subcategory: 'mineral-sunscreens',
    description: 'A mineral-based sunscreen with zinc oxide and titanium dioxide for sensitive skin.',
    images: [
      { url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Zinc Oxide',
      'Titanium Dioxide',
      'Cetearyl Alcohol',
      'Glycerin',
      'Ceramide NP',
      'Ceramide AP',
      'Ceramide EOP',
      'Hyaluronic Acid',
      'Dimethicone',
      'Sodium Hyaluronate',
      'Tocopherol',
      'Carbomer',
      'Sodium Lauroyl Lactylate',
      'Potassium Phosphate',
      'Disodium EDTA',
      'Phenoxyethanol',
      'Methylparaben',
      'Propylparaben',
    ],
    size: '50ml',
    priceRange: { min: 12, max: 18, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$12-18', currency: 'USD', retailer: 'amazon' },
      { country: 'Canada', countryCode: 'CA', available: true, price: 'CA$15-22', currency: 'CAD', retailer: 'amazon' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£10-15', currency: 'GBP', retailer: 'amazon' },
    ],
    targetSkinTypes: ['sensitive', 'dry', 'normal'],
    targetConcerns: ['sun protection', 'sensitivity'],
    keyIngredients: ['Zinc Oxide', 'Titanium Dioxide', 'Ceramide NP'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['drugstore', 'mineral', 'sensitive-skin', 'fragrance-free'],
  },
  {
    id: 'la_roche_posay_anthelios',
    name: 'Anthelios Ultra-Light SPF 50',
    brand: 'La Roche-Posay',
    category: 'sunscreens',
    subcategory: 'chemical-sunscreens',
    description: 'A lightweight, non-greasy sunscreen with broad-spectrum SPF 50 protection.',
    images: [
      { url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Homosalate',
      'Octisalate',
      'Avobenzone',
      'Octocrylene',
      'Zinc Oxide',
      'Silica',
      'Alcohol Denat.',
      'Dimethicone',
      'Glycerin',
      'PEG-8',
      'Sodium Hyaluronate',
      'Tocopherol',
      'Caprylyl Glycol',
      'Phenoxyethanol',
      'Acrylates/Dimethicone Copolymer',
      'Disodium EDTA',
      'Potassium Cetyl Phosphate',
      'Sodium Hydroxide',
    ],
    size: '50ml',
    priceRange: { min: 20, max: 28, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$20-28', currency: 'USD', retailer: 'ulta' },
      { country: 'France', countryCode: 'FR', available: true, price: '€18-24', currency: 'EUR', retailer: 'sephora' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£16-22', currency: 'GBP', retailer: 'boots' },
      { country: 'Canada', countryCode: 'CA', available: true, price: 'CA$25-32', currency: 'CAD', retailer: 'amazon' },
    ],
    targetSkinTypes: ['all'],
    targetConcerns: ['sun protection', 'premature aging', 'hyperpigmentation'],
    keyIngredients: ['Avobenzone', 'Octocrylene', 'Zinc Oxide'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['french-pharmacy', 'broad-spectrum', 'lightweight'],
  },
  {
    id: 'supergoop_unseen',
    name: 'Unseen Sunscreen SPF 40',
    brand: 'Supergoop!',
    category: 'sunscreens',
    subcategory: 'chemical-sunscreens',
    description: 'An invisible, weightless sunscreen that feels like a primer.',
    images: [
      { url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Dimethicone',
      'Red Algae',
      'Meadowfoam Seed Oil',
      'Avobenzone',
      'Homosalate',
      'Octisalate',
      'Octocrylene',
      'Caprylyl Methicone',
      'Dimethicone Crosspolymer',
      'Tocopherol',
      'Caprylyl Glycol',
      'Phenoxyethanol',
    ],
    size: '50ml',
    priceRange: { min: 34, max: 38, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$34-38', currency: 'USD', retailer: 'sephora' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£28-32', currency: 'GBP', retailer: 'cult-beauty' },
    ],
    targetSkinTypes: ['all'],
    targetConcerns: ['sun protection', 'makeup-primer'],
    keyIngredients: ['Avobenzone', 'Red Algae', 'Meadowfoam Seed Oil'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['premium', 'invisible', 'makeup-primer'],
  },
  {
    id: 'beauty_of_joseon_sunscreen',
    name: 'Relief Sun: Rice + Probiotics SPF 50+',
    brand: 'Beauty of Joseon',
    category: 'sunscreens',
    subcategory: 'chemical-sunscreens',
    description: 'A lightweight K-beauty sunscreen with rice extract and probiotics.',
    images: [
      { url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Ethylhexyl Methoxycinnamate',
      'Ethylhexyl Salicylate',
      'Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine',
      'Rice Extract',
      'Probiotics',
      'Niacinamide',
      'Glycerin',
      'Butylene Glycol',
      'Caprylyl Glycol',
      'Phenoxyethanol',
    ],
    size: '50ml',
    priceRange: { min: 10, max: 14, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$10-14', currency: 'USD', retailer: 'amazon' },
      { country: 'South Korea', countryCode: 'KR', available: true, price: '₩15,000-20,000', currency: 'KRW', retailer: 'yesstyle' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£8-12', currency: 'GBP', retailer: 'yesstyle' },
    ],
    targetSkinTypes: ['all'],
    targetConcerns: ['sun protection', 'hydration'],
    keyIngredients: ['Rice Extract', 'Probiotics', 'Niacinamide'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['k-beauty', 'affordable', 'lightweight'],
  },
  {
    id: 'elta_md_uv_clear',
    name: 'UV Clear Broad-Spectrum SPF 46',
    brand: 'EltaMD',
    category: 'sunscreens',
    subcategory: 'chemical-sunscreens',
    description: 'A lightweight, oil-free sunscreen with niacinamide for acne-prone skin.',
    images: [
      { url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Zinc Oxide',
      'Octinoxate',
      'Niacinamide',
      'Sodium Hyaluronate',
      'Tocopherol',
      'Lactic Acid',
      'Caprylyl Glycol',
      'Phenoxyethanol',
    ],
    size: '48g',
    priceRange: { min: 35, max: 40, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$35-40', currency: 'USD', retailer: 'amazon' },
      { country: 'Canada', countryCode: 'CA', available: true, price: 'CA$45-50', currency: 'CAD', retailer: 'amazon' },
    ],
    targetSkinTypes: ['oily', 'acne-prone', 'sensitive'],
    targetConcerns: ['sun protection', 'acne', 'oiliness'],
    keyIngredients: ['Zinc Oxide', 'Niacinamide', 'Sodium Hyaluronate'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['premium', 'acne-friendly', 'oil-free'],
  },
];


