/**
 * Toners & Essences Database - Global Products
 * Hydrating toners, exfoliating toners, first treatment essences
 */

import { GlobalProduct } from '../product-database-structure';

export const TONERS: GlobalProduct[] = [
  // Hydrating Toners
  {
    id: 'klairs_toner',
    name: 'Supple Preparation Unscented Toner',
    brand: 'Klairs',
    category: 'toners',
    subcategory: 'hydrating-toners',
    description: 'A gentle, hydrating toner with hyaluronic acid and beta-glucan for sensitive skin.',
    images: [
      { url: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Butylene Glycol',
      'Beta-Glucan',
      'Sodium Hyaluronate',
      'Allantoin',
      'Aloe Barbadensis Leaf Extract',
      'Centella Asiatica Extract',
      'Portulaca Oleracea Extract',
      '1,2-Hexanediol',
      'Caprylyl Glycol',
      'Ethylhexylglycerin',
      'Phenoxyethanol',
    ],
    size: '180ml',
    priceRange: { min: 18, max: 22, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$18-22', currency: 'USD', retailer: 'amazon' },
      { country: 'South Korea', countryCode: 'KR', available: true, price: '₩25,000-30,000', currency: 'KRW', retailer: 'yesstyle' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£15-18', currency: 'GBP', retailer: 'yesstyle' },
    ],
    targetSkinTypes: ['sensitive', 'dry', 'normal'],
    targetConcerns: ['dryness', 'sensitivity', 'hydration'],
    keyIngredients: ['Beta-Glucan', 'Sodium Hyaluronate', 'Centella Asiatica Extract'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['k-beauty', 'sensitive-skin', 'hydrating', 'fragrance-free'],
  },
  {
    id: 'hada_labo_toner',
    name: 'Gokujun Hyaluronic Lotion',
    brand: 'Hada Labo',
    category: 'toners',
    subcategory: 'hydrating-toners',
    description: 'A Japanese hydrating toner with 5 types of hyaluronic acid for intense moisture.',
    images: [
      { url: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Butylene Glycol',
      'Glycerin',
      'Sodium Hyaluronate',
      'Hydrolyzed Hyaluronic Acid',
      'Sodium Acetylated Hyaluronate',
      'Hydroxypropyltrimonium Hyaluronate',
      'Sodium Hyaluronate Crosspolymer',
      'Methylparaben',
      'Propylparaben',
    ],
    size: '170ml',
    priceRange: { min: 12, max: 16, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$12-16', currency: 'USD', retailer: 'amazon' },
      { country: 'Japan', countryCode: 'JP', available: true, price: '¥1,200-1,600', currency: 'JPY', retailer: 'amazon' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£10-14', currency: 'GBP', retailer: 'amazon' },
    ],
    targetSkinTypes: ['dry', 'normal', 'combination'],
    targetConcerns: ['dryness', 'hydration'],
    keyIngredients: ['Sodium Hyaluronate', 'Hydrolyzed Hyaluronic Acid', 'Sodium Hyaluronate Crosspolymer'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['japanese', 'hydrating', 'affordable'],
  },
  {
    id: 'thayers_toner',
    name: 'Witch Hazel Facial Toner',
    brand: 'Thayers',
    category: 'toners',
    subcategory: 'hydrating-toners',
    description: 'An alcohol-free toner with witch hazel and rose water for gentle hydration.',
    images: [
      { url: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Purified Water',
      'Witch Hazel',
      'Rose Petal Water',
      'Glycerin',
      'Aloe Barbadensis Leaf Juice',
      'Citric Acid',
      'Grapefruit Seed Extract',
    ],
    size: '355ml',
    priceRange: { min: 10, max: 14, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$10-14', currency: 'USD', retailer: 'amazon' },
      { country: 'Canada', countryCode: 'CA', available: true, price: 'CA$12-16', currency: 'CAD', retailer: 'amazon' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£8-12', currency: 'GBP', retailer: 'amazon' },
    ],
    targetSkinTypes: ['all'],
    targetConcerns: ['hydration', 'soothing'],
    keyIngredients: ['Witch Hazel', 'Rose Petal Water', 'Aloe Barbadensis Leaf Juice'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['affordable', 'alcohol-free', 'natural'],
  },

  // Exfoliating Toners
  {
    id: 'ordinary_glycolic_toner',
    name: 'Glycolic Acid 7% Toning Solution',
    brand: 'The Ordinary',
    category: 'toners',
    subcategory: 'exfoliating-toners',
    description: 'An exfoliating toner with 7% glycolic acid to improve skin texture and radiance.',
    images: [
      { url: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Glycolic Acid',
      'Aminomethyl Propanol',
      'Glycerin',
      'Aloe Barbadensis Leaf Water',
      'Ginseng Root Extract',
      'Tasmannia Lanceolata Fruit/Leaf Extract',
      '1,2-Hexanediol',
      'Propanediol',
      'Citric Acid',
      'Polysorbate 20',
    ],
    size: '240ml',
    priceRange: { min: 8, max: 10, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$8-10', currency: 'USD', retailer: 'amazon' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£7-9', currency: 'GBP', retailer: 'cult-beauty' },
    ],
    targetSkinTypes: ['normal', 'oily', 'combination'],
    targetConcerns: ['texture', 'fine lines', 'hyperpigmentation', 'acne'],
    keyIngredients: ['Glycolic Acid', 'Ginseng Root Extract', 'Aloe Barbadensis Leaf Water'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['affordable', 'exfoliating', 'aha', 'vegan'],
  },
  {
    id: 'paula_choice_bha_toner',
    name: '2% BHA Liquid Exfoliant',
    brand: "Paula's Choice",
    category: 'toners',
    subcategory: 'exfoliating-toners',
    description: 'A leave-on exfoliant with 2% salicylic acid to unclog pores and smooth skin texture.',
    images: [
      { url: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Methylpropanediol',
      'Salicylic Acid',
      'Camellia Oleifera Leaf Extract',
      'Sodium Hydroxide',
      'Butylene Glycol',
      'Polysorbate 20',
      'Tetrasodium EDTA',
      'Ethylhexylglycerin',
      'Phenoxyethanol',
      'Blue 1',
    ],
    size: '118ml',
    priceRange: { min: 30, max: 35, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$30-35', currency: 'USD', retailer: 'sephora' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£25-30', currency: 'GBP', retailer: 'cult-beauty' },
    ],
    targetSkinTypes: ['oily', 'combination', 'acne-prone'],
    targetConcerns: ['acne', 'pores', 'blackheads', 'texture'],
    keyIngredients: ['Salicylic Acid', 'Camellia Oleifera Leaf Extract'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['premium', 'bha', 'acne-friendly', 'pore-minimizing'],
  },

  // First Treatment Essences
  {
    id: 'missha_first_essence',
    name: 'Time Revolution The First Treatment Essence',
    brand: 'Missha',
    category: 'toners',
    subcategory: 'first-treatment-essences',
    description: 'A fermented first treatment essence with 80% fermented yeast extract for skin renewal.',
    images: [
      { url: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Saccharomyces Ferment Filtrate',
      'Water',
      'Butylene Glycol',
      'Glycerin',
      'Niacinamide',
      'Bifida Ferment Lysate',
      'Lactobacillus Ferment',
      'Sodium Hyaluronate',
      '1,2-Hexanediol',
      'Caprylyl Glycol',
      'Ethylhexylglycerin',
      'Phenoxyethanol',
    ],
    size: '150ml',
    priceRange: { min: 25, max: 32, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$25-32', currency: 'USD', retailer: 'amazon' },
      { country: 'South Korea', countryCode: 'KR', available: true, price: '₩35,000-45,000', currency: 'KRW', retailer: 'yesstyle' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£20-28', currency: 'GBP', retailer: 'yesstyle' },
    ],
    targetSkinTypes: ['all'],
    targetConcerns: ['texture', 'brightening', 'hydration'],
    keyIngredients: ['Saccharomyces Ferment Filtrate', 'Bifida Ferment Lysate', 'Niacinamide'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['k-beauty', 'fermented', 'first-treatment-essence'],
  },
  {
    id: 'cosrx_galactomyces',
    name: 'Galactomyces 95 Tone Balancing Essence',
    brand: 'COSRX',
    category: 'toners',
    subcategory: 'first-treatment-essences',
    description: 'A fermented essence with 95% galactomyces ferment filtrate for brightening and hydration.',
    images: [
      { url: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Galactomyces Ferment Filtrate',
      'Butylene Glycol',
      '1,2-Hexanediol',
      'Betaine',
      'Niacinamide',
      'Allantoin',
      'Sodium Hyaluronate',
      'Caprylyl Glycol',
      'Ethylhexylglycerin',
      'Phenoxyethanol',
    ],
    size: '100ml',
    priceRange: { min: 15, max: 20, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$15-20', currency: 'USD', retailer: 'amazon' },
      { country: 'South Korea', countryCode: 'KR', available: true, price: '₩22,000-28,000', currency: 'KRW', retailer: 'yesstyle' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£12-18', currency: 'GBP', retailer: 'yesstyle' },
    ],
    targetSkinTypes: ['all'],
    targetConcerns: ['brightening', 'texture', 'hydration'],
    keyIngredients: ['Galactomyces Ferment Filtrate', 'Niacinamide', 'Sodium Hyaluronate'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['k-beauty', 'fermented', 'affordable', 'brightening'],
  },
];


