/**
 * Treatments Database - Global Products
 * Retinoids, acids (AHA/BHA), peptides, spot treatments
 */

import { GlobalProduct } from '../product-database-structure';

export const TREATMENTS: GlobalProduct[] = [
  // Retinoids
  {
    id: 'ordinary_retinol_05',
    name: 'Retinol 0.5% in Squalane',
    brand: 'The Ordinary',
    category: 'treatments',
    subcategory: 'retinoids',
    description: 'A water-free solution with 0.5% pure retinol in squalane for anti-aging benefits.',
    images: [
      { url: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Squalane',
      'Retinol',
      'Rosmarinus Officinalis Leaf Extract',
      'Tocopherol',
    ],
    size: '30ml',
    priceRange: { min: 8, max: 10, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$8-10', currency: 'USD', retailer: 'amazon' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£7-9', currency: 'GBP', retailer: 'cult-beauty' },
      { country: 'Canada', countryCode: 'CA', available: true, price: 'CA$10-12', currency: 'CAD', retailer: 'amazon' },
    ],
    targetSkinTypes: ['normal', 'oily', 'combination'],
    targetConcerns: ['fine lines', 'wrinkles', 'texture', 'acne'],
    keyIngredients: ['Retinol', 'Squalane', 'Tocopherol'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['affordable', 'anti-aging', 'retinol', 'vegan'],
  },
  {
    id: 'ordinary_retinol_1',
    name: 'Retinol 1% in Squalane',
    brand: 'The Ordinary',
    category: 'treatments',
    subcategory: 'retinoids',
    description: 'A high-strength retinol serum for advanced anti-aging benefits.',
    images: [
      { url: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Squalane',
      'Retinol',
      'Rosmarinus Officinalis Leaf Extract',
      'Tocopherol',
    ],
    size: '30ml',
    priceRange: { min: 9, max: 11, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$9-11', currency: 'USD', retailer: 'amazon' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£8-10', currency: 'GBP', retailer: 'cult-beauty' },
    ],
    targetSkinTypes: ['normal', 'oily', 'combination'],
    targetConcerns: ['fine lines', 'wrinkles', 'texture', 'acne'],
    keyIngredients: ['Retinol', 'Squalane', 'Tocopherol'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['affordable', 'anti-aging', 'high-strength', 'retinol'],
  },
  {
    id: 'paula_choice_retinol',
    name: 'Clinical 1% Retinol Treatment',
    brand: "Paula's Choice",
    category: 'treatments',
    subcategory: 'retinoids',
    description: 'A potent retinol treatment with 1% retinol and peptides for advanced anti-aging.',
    images: [
      { url: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Retinol',
      'Peptides',
      'Ceramides',
      'Niacinamide',
      'Glycerin',
      'Sodium Hyaluronate',
      'Tocopherol',
      'Allantoin',
      'Butylene Glycol',
      'Caprylyl Glycol',
      'Phenoxyethanol',
    ],
    size: '30ml',
    priceRange: { min: 45, max: 52, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$45-52', currency: 'USD', retailer: 'sephora' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£38-45', currency: 'GBP', retailer: 'cult-beauty' },
    ],
    targetSkinTypes: ['normal', 'oily', 'combination'],
    targetConcerns: ['fine lines', 'wrinkles', 'texture', 'anti-aging'],
    keyIngredients: ['Retinol', 'Peptides', 'Ceramides', 'Niacinamide'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['premium', 'anti-aging', 'retinol', 'peptides'],
  },

  // Acids (AHA/BHA)
  {
    id: 'ordinary_glycolic_acid',
    name: 'Glycolic Acid 7% Toning Solution',
    brand: 'The Ordinary',
    category: 'treatments',
    subcategory: 'acids',
    description: 'An exfoliating toner with 7% glycolic acid to improve skin texture and radiance.',
    images: [
      { url: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Glycolic Acid',
      'Aminomethyl Propanol',
      'Glycerin',
      'Aloe Barbadensis Leaf Water',
      'Ginseng Root Extract',
      'Tasmannia Lanceolata Fruit/Leaf Extract',
      '1,2-Hexanediol',
      'Propanediol',
      'Citric Acid',
      'Polysorbate 20',
    ],
    size: '240ml',
    priceRange: { min: 8, max: 10, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$8-10', currency: 'USD', retailer: 'amazon' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£7-9', currency: 'GBP', retailer: 'cult-beauty' },
    ],
    targetSkinTypes: ['normal', 'oily', 'combination'],
    targetConcerns: ['texture', 'fine lines', 'hyperpigmentation', 'acne'],
    keyIngredients: ['Glycolic Acid', 'Ginseng Root Extract', 'Aloe Barbadensis Leaf Water'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['affordable', 'exfoliating', 'aha', 'vegan'],
  },
  {
    id: 'paula_choice_bha',
    name: '2% BHA Liquid Exfoliant',
    brand: "Paula's Choice",
    category: 'treatments',
    subcategory: 'acids',
    description: 'A leave-on exfoliant with 2% salicylic acid to unclog pores and smooth skin texture.',
    images: [
      { url: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Methylpropanediol',
      'Salicylic Acid',
      'Camellia Oleifera Leaf Extract',
      'Sodium Hydroxide',
      'Butylene Glycol',
      'Polysorbate 20',
      'Tetrasodium EDTA',
      'Ethylhexylglycerin',
      'Phenoxyethanol',
      'Blue 1',
    ],
    size: '118ml',
    priceRange: { min: 30, max: 35, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$30-35', currency: 'USD', retailer: 'sephora' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£25-30', currency: 'GBP', retailer: 'cult-beauty' },
      { country: 'Canada', countryCode: 'CA', available: true, price: 'CA$38-45', currency: 'CAD', retailer: 'sephora' },
    ],
    targetSkinTypes: ['oily', 'combination', 'acne-prone'],
    targetConcerns: ['acne', 'pores', 'blackheads', 'texture'],
    keyIngredients: ['Salicylic Acid', 'Camellia Oleifera Leaf Extract'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['premium', 'bha', 'acne-friendly', 'pore-minimizing'],
  },
  {
    id: 'cosrx_bha_blackhead',
    name: 'BHA Blackhead Power Liquid',
    brand: 'COSRX',
    category: 'treatments',
    subcategory: 'acids',
    description: 'A gentle BHA treatment with betaine salicylate to clear blackheads and minimize pores.',
    images: [
      { url: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Betaine Salicylate',
      'Butylene Glycol',
      'Sodium Hyaluronate',
      'Willow Bark Extract',
      'Niacinamide',
      '1,2-Hexanediol',
      'Caprylyl Glycol',
      'Ethylhexylglycerin',
      'Phenoxyethanol',
    ],
    size: '100ml',
    priceRange: { min: 12, max: 16, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$12-16', currency: 'USD', retailer: 'amazon' },
      { country: 'South Korea', countryCode: 'KR', available: true, price: '₩18,000-25,000', currency: 'KRW', retailer: 'yesstyle' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£10-14', currency: 'GBP', retailer: 'yesstyle' },
    ],
    targetSkinTypes: ['oily', 'combination', 'acne-prone'],
    targetConcerns: ['blackheads', 'pores', 'acne', 'texture'],
    keyIngredients: ['Betaine Salicylate', 'Willow Bark Extract', 'Niacinamide'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['k-beauty', 'bha', 'acne-friendly', 'affordable'],
  },
  {
    id: 'ordinary_lactic_acid',
    name: 'Lactic Acid 10% + HA',
    brand: 'The Ordinary',
    category: 'treatments',
    subcategory: 'acids',
    description: 'A gentle AHA exfoliant with 10% lactic acid to improve skin texture and radiance.',
    images: [
      { url: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Lactic Acid',
      'Sodium Hyaluronate',
      'Glycerin',
      'Tasmannia Lanceolata Fruit/Leaf Extract',
      '1,2-Hexanediol',
      'Caprylyl Glycol',
      'Phenoxyethanol',
    ],
    size: '30ml',
    priceRange: { min: 7, max: 9, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$7-9', currency: 'USD', retailer: 'amazon' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£6-8', currency: 'GBP', retailer: 'cult-beauty' },
    ],
    targetSkinTypes: ['normal', 'oily', 'combination'],
    targetConcerns: ['texture', 'fine lines', 'hyperpigmentation'],
    keyIngredients: ['Lactic Acid', 'Sodium Hyaluronate'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['affordable', 'aha', 'exfoliating', 'vegan'],
  },
  {
    id: 'drunk_elephant_tlc',
    name: 'T.L.C. Framboos Glycolic Night Serum',
    brand: 'Drunk Elephant',
    category: 'treatments',
    subcategory: 'acids',
    description: 'A powerful AHA/BHA blend with 12% glycolic acid and 1% salicylic acid for overnight exfoliation.',
    images: [
      { url: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Glycolic Acid',
      'Salicylic Acid',
      'Lactic Acid',
      'Citric Acid',
      'Tartaric Acid',
      'Glycerin',
      'Sodium Hyaluronate',
      'Bearberry Extract',
      'Butylene Glycol',
      'Caprylyl Glycol',
      'Phenoxyethanol',
    ],
    size: '30ml',
    priceRange: { min: 90, max: 95, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$90-95', currency: 'USD', retailer: 'sephora' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£75-85', currency: 'GBP', retailer: 'cult-beauty' },
    ],
    targetSkinTypes: ['normal', 'oily', 'combination'],
    targetConcerns: ['texture', 'fine lines', 'acne', 'hyperpigmentation'],
    keyIngredients: ['Glycolic Acid', 'Salicylic Acid', 'Lactic Acid'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['luxury', 'aha-bha-blend', 'exfoliating', 'clean-beauty'],
  },

  // Spot Treatments
  {
    id: 'ordinary_azelaic_acid',
    name: 'Azelaic Acid Suspension 10%',
    brand: 'The Ordinary',
    category: 'treatments',
    subcategory: 'spot-treatments',
    description: 'A brightening and blemish treatment with 10% azelaic acid.',
    images: [
      { url: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Dimethyl Isosorbide',
      'Azelaic Acid',
      'Dimethicone',
      'Isoceteth-20',
      'Polysorbate 20',
      'Phenoxyethanol',
      'Chlorphenesin',
    ],
    size: '30ml',
    priceRange: { min: 8, max: 10, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$8-10', currency: 'USD', retailer: 'amazon' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£7-9', currency: 'GBP', retailer: 'cult-beauty' },
    ],
    targetSkinTypes: ['all'],
    targetConcerns: ['acne', 'hyperpigmentation', 'redness'],
    keyIngredients: ['Azelaic Acid'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['affordable', 'acne-treatment', 'brightening'],
  },
];


