/**
 * Cleansers Database - Global Products
 * Oil cleansers, foaming cleansers, gel cleansers, balm cleansers, micellar waters
 */

import { GlobalProduct } from '../product-database-structure';

export const CLEANSERS: GlobalProduct[] = [
  // Oil Cleansers
  {
    id: 'dhc_deep_cleansing_oil',
    name: 'Deep Cleansing Oil',
    brand: 'DHC',
    category: 'cleansers',
    subcategory: 'oil-cleansers',
    description: 'A bestselling Japanese oil cleanser that effectively removes makeup and impurities while maintaining skin moisture.',
    images: [
      { url: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Olive Fruit Oil',
      'Caprylic/Capric Triglyceride',
      'Sorbeth-30 Tetraoleate',
      'PEG-20 Glyceryl Triisostearate',
      'Phenoxyethanol',
      'Tocopherol',
      'Rosmarinus Officinalis Leaf Extract',
    ],
    size: '200ml',
    priceRange: { min: 12, max: 18, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$12-18', currency: 'USD', retailer: 'amazon' },
      { country: 'Japan', countryCode: 'JP', available: true, price: '¥1,200-1,800', currency: 'JPY', retailer: 'amazon' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£10-15', currency: 'GBP', retailer: 'cult-beauty' },
      { country: 'Canada', countryCode: 'CA', available: true, price: 'CA$15-22', currency: 'CAD', retailer: 'amazon' },
      { country: 'Australia', countryCode: 'AU', available: true, price: 'AU$18-25', currency: 'AUD', retailer: 'amazon' },
    ],
    targetSkinTypes: ['all'],
    targetConcerns: ['makeup-removal', 'deep-cleansing'],
    keyIngredients: ['Olive Fruit Oil', 'Tocopherol'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['japanese', 'oil-cleanser', 'makeup-remover'],
  },
  {
    id: 'banila_co_clean_it_zero',
    name: 'Clean It Zero Cleansing Balm',
    brand: 'Banila Co',
    category: 'cleansers',
    subcategory: 'balm-cleansers',
    description: 'A cult-favorite K-beauty balm cleanser that transforms from balm to oil to milk, effectively removing all makeup.',
    images: [
      { url: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Ethylhexyl Palmitate',
      'PEG-20 Glyceryl Triisostearate',
      'Cetyl Ethylhexanoate',
      'Synthetic Wax',
      'Polyethylene',
      'Water',
      'Butylene Glycol',
      'Glycerin',
      'Rosa Centifolia Flower Extract',
      'Phenoxyethanol',
      'Tocopherol',
    ],
    size: '100ml',
    priceRange: { min: 15, max: 22, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$15-22', currency: 'USD', retailer: 'amazon' },
      { country: 'South Korea', countryCode: 'KR', available: true, price: '₩18,000-25,000', currency: 'KRW', retailer: 'yesstyle' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£12-18', currency: 'GBP', retailer: 'cult-beauty' },
    ],
    targetSkinTypes: ['all'],
    targetConcerns: ['makeup-removal', 'deep-cleansing'],
    keyIngredients: ['Ethylhexyl Palmitate', 'Rosa Centifolia Flower Extract'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['k-beauty', 'balm-cleanser', 'makeup-remover', 'cult-favorite'],
  },

  // Foaming Cleansers
  {
    id: 'cerave_foaming_cleanser',
    name: 'Foaming Facial Cleanser',
    brand: 'CeraVe',
    category: 'cleansers',
    subcategory: 'foaming-cleansers',
    description: 'A gentle foaming cleanser with ceramides and niacinamide for normal to oily skin.',
    images: [
      { url: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Cocamidopropyl Hydroxysultaine',
      'Glycerin',
      'Sodium Lauroamphoacetate',
      'Sodium Methyl Cocoyl Taurate',
      'Ceramide NP',
      'Ceramide AP',
      'Ceramide EOP',
      'Niacinamide',
      'Sodium Hyaluronate',
      'Cholesterol',
      'Disodium EDTA',
      'Dipropylene Glycol',
      'Phenoxyethanol',
      'Methylparaben',
      'Propylparaben',
    ],
    size: '355ml',
    priceRange: { min: 10, max: 15, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$10-15', currency: 'USD', retailer: 'amazon' },
      { country: 'Canada', countryCode: 'CA', available: true, price: 'CA$12-18', currency: 'CAD', retailer: 'amazon' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£8-12', currency: 'GBP', retailer: 'amazon' },
      { country: 'Australia', countryCode: 'AU', available: true, price: 'AU$15-22', currency: 'AUD', retailer: 'amazon' },
    ],
    targetSkinTypes: ['oily', 'combination', 'normal'],
    targetConcerns: ['oiliness', 'pores'],
    keyIngredients: ['Ceramide NP', 'Niacinamide', 'Sodium Hyaluronate'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['drugstore', 'ceramides', 'foaming', 'fragrance-free'],
  },
  {
    id: 'cosrx_low_ph_cleanser',
    name: 'Low pH Good Morning Gel Cleanser',
    brand: 'COSRX',
    category: 'cleansers',
    subcategory: 'gel-cleansers',
    description: 'A gentle, low-pH gel cleanser with BHA and tea tree oil, perfect for morning routine.',
    images: [
      { url: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Cocamidopropyl Betaine',
      'Sodium Lauroamphoacetate',
      'Sodium Methyl Cocoyl Taurate',
      'Betaine Salicylate',
      'Tea Tree Leaf Oil',
      'Allantoin',
      'Butylene Glycol',
      'Glycerin',
      'Sodium Chloride',
      'Disodium EDTA',
      'Ethylhexylglycerin',
      'Phenoxyethanol',
    ],
    size: '150ml',
    priceRange: { min: 8, max: 12, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$8-12', currency: 'USD', retailer: 'amazon' },
      { country: 'South Korea', countryCode: 'KR', available: true, price: '₩12,000-18,000', currency: 'KRW', retailer: 'yesstyle' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£7-10', currency: 'GBP', retailer: 'cult-beauty' },
    ],
    targetSkinTypes: ['oily', 'combination', 'acne-prone'],
    targetConcerns: ['acne', 'pores', 'oiliness'],
    keyIngredients: ['Betaine Salicylate', 'Tea Tree Leaf Oil', 'Allantoin'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['k-beauty', 'low-ph', 'bha', 'acne-friendly'],
  },
  {
    id: 'la_roche_posay_toleriane_foaming',
    name: 'Toleriane Purifying Foaming Cleanser',
    brand: 'La Roche-Posay',
    category: 'cleansers',
    subcategory: 'foaming-cleansers',
    description: 'A gentle foaming cleanser for normal to oily sensitive skin with ceramides and niacinamide.',
    images: [
      { url: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800&h=800&fit=crop&q=90', type: 'primary' },
    ],
    ingredients: [
      'Water',
      'Glycerin',
      'Pentaerythrityl Tetraisostearate',
      'Niacinamide',
      'Ceramide NP',
      'Sodium Lauroamphoacetate',
      'Cocamidopropyl Betaine',
      'Sodium Trideceth Sulfate',
      'Disodium EDTA',
      'Caprylyl Glycol',
      'Citric Acid',
      'Sodium Hydroxide',
    ],
    size: '400ml',
    priceRange: { min: 15, max: 20, currency: 'USD' },
    regionalAvailability: [
      { country: 'United States', countryCode: 'US', available: true, price: '$15-20', currency: 'USD', retailer: 'ulta' },
      { country: 'France', countryCode: 'FR', available: true, price: '€12-16', currency: 'EUR', retailer: 'sephora' },
      { country: 'United Kingdom', countryCode: 'GB', available: true, price: '£12-16', currency: 'GBP', retailer: 'boots' },
      { country: 'Canada', countryCode: 'CA', available: true, price: 'CA$18-24', currency: 'CAD', retailer: 'amazon' },
    ],
    targetSkinTypes: ['sensitive', 'oily', 'combination'],
    targetConcerns: ['sensitivity', 'oiliness'],
    keyIngredients: ['Niacinamide', 'Ceramide NP'],
    verified: true,
    lastVerified: '2024-01-01',
    tags: ['french-pharmacy', 'sensitive-skin', 'ceramides', 'fragrance-free'],
  },
];


